name: Update Tide JSON

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run tide builder
        run: python build_tide.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          
          # 変更がある場合のみコミットしてプッシュする（変更がなければ安全に終了）
          if ! git diff --staged --exit-code --quiet; then
            git commit -m "auto update tide json"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi


